---
title: "Real-Time Indoor Location Positioning"
author: "paula@smu, J-Dog, Miller"
date: January 12, 2018
abstract: |
  The expected content of a case study for classwork is described.
  An alternative content is proposedand described.
  Both a formal written document (such as written here) or
  a Jupyter Notebook with appropriate content may be presented
lang: en-US
class: man
# figsintext: true
numbersections: true
encoding: UTF-8
bibliography: references.bib
biblio-style: apalike
output:
  bookdown::pdf_document2:
     citation_package: natbib
     keep_tex: true
     toc: false
header-includes:
   - \usepackage{amsmath}
   - \usepackage[utf8]{inputenc}
   - \usepackage[T1]{fontenc}
   - \usepackage{setspace}
   - \usepackage{hyperref}
   - \onehalfspacing
   - \setcitestyle{numbers,square,super}
   - \newcommand\numberthis{\addtocounter{equation}{1}\tag{\theequation}}
editor_options: 
  chunk_output_type: console
---

```{r, lib-read, results='hide', message=FALSE, include=FALSE, echo=FALSE}
# libraries
library(tidyverse)
source('./functions.R')

# set a random seed for repodicibility
set.seed(42)


# load the data
offline <- readData()
online <- readData(filename = './online.data.txt',
                   subMacs = unique(offline$mac))

macAddresses <- sort(unique(offline$mac))

# create a unique position identifier
offline$posXY <- paste(offline$posX, offline$posY, sep = '-')
online$posXY <- paste(online$posX, online$posY, sep = '-')




```

# Introduction

TODO \cite{NolanLang}

# Methods

## Describe how you prepared the data.

ddescription (stuart)

## What modeling method you used

model description (stuart)

## Describe how you estimated your error and found the best fit ASSUMING you CANNOT USE THE ONLINE DATA.

kold cross validation (paul)



# Results

Use a table to describe the results (markdown table)

## Describe the best fit for the data.

I think this is just k, plots that show error over k (1-15)

There are 2 macIDs located at the same position.  
Does one give better performance than the other?
(00:0f:a3:39:e1:c0, 00:0f:a3:39:dd:cd)


## What about using them both?

Use c0, then use cd, than use cd and c0

a plot with all three models

# Conclusion

## What is the drawback (if any of using this method to real-time locate an object)?

KNN is slow. calculation scales as n^2/2. Considers the whole dataset.

Describe a method that may be an improvement based on your perceived drawbacks.

Linear regression, assuming the assumptions are met

* Variance of the residuals is constant
* Normally distributed residuals
* No outlier + leverage points

\newpage

\appendix

# Code


```
A code block
cool
cool
code
yo
```


