---
title: "web_scrape"
author: "Justin Howard, Stuart Miller, Paul Adams"
date: "September 10, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(XML)
ubase = "http://www.cherryblossom.org/"
menURLs = 
  c("results/1999/cb99m.html", "results/2000/Cb003m.htm", "results/2001/oof_m.html",
    "results/2002/oofm.htm", "results/2003/CB03-M.HTM",
    "results/2004/men.htm", "results/2005/CB05-M.htm", 
    "results/2006/men.htm", "results/2007/men.htm", 
    "results/2008/men.htm", "results/2009/09cucb-M.htm",
    "results/2010/2010cucb10m-m.htm", 
    "results/2011/2011cucb10m-m.htm",
    "results/2012/2012cucb10m-m.htm")

urls = paste(ubase, menURLs, sep = "")

urls[1:3]


extractResTable =
  # takes a list of websites from the cherry blossom race
  # a list of years corresponding to the year the result is for
  # and the gender of the participant
  # Retrieve data from web site, 
  # find the preformatted text,
  # and write lines or return as a character vector.
  # returns a list of strings corrsponding to lines in the web url
  function(url = "http://www.cherryblossom.org/results/2009/09cucb-F.htm",
           year = 1999, sex = "male", file = NULL)
  {
    doc = htmlParse(url)

    if (year == 2000) {
      # Get preformatted text from 4th font element
      # The top file is ill formed so the <pre> search doesn't work.
      ff = getNodeSet(doc, "//font")
      txt = xmlValue(ff[[4]])
      els = strsplit(txt, "\r\n")[[1]]
    }
    else if (year == 2009 & sex == "male") {
      # Get preformatted text from <div class="Section1"> element
      # Each line of results is in a <pre> element
      div1 = getNodeSet(doc, "//div[@class='Section1']")
      pres = getNodeSet(div1[[1]], "//pre")
      els = sapply(pres, xmlValue)
      els = gsub("Â", "", els)
    }
    else if (year == 1999) {
      # Get preformatted text from <pre> elements
      pres = getNodeSet(doc, "//pre")
      txt = xmlValue(pres[[1]])
      els = strsplit(txt, "\n")[[1]]   
    } 
    else {
      # Get preformatted text from <pre> elements
      pres = getNodeSet(doc, "//pre")
      txt = xmlValue(pres[[1]])
      els = strsplit(txt, "\r\n")[[1]]   
    } 
    if (is.null(file)) return(els)
    # Write the lines as a text file.
    writeLines(els, con = file)
  }


years = 1999:2012
menTables = mapply(extractResTable, url = urls, year = years)
names(menTables) = years
sapply(menTables, length)

#womenTables = mapply(extractResTable, url = urls, 
#                       year = years, sex = rep("female", 14))
#names(womenTables) = years
#sapply(womenTables, length)


save(menTables, file = "CBMenTextTables.rda")
```
```{r}
men_2009<-extractResTable(url = urls[11], year = 2009, sex = 'male')
men_2008<-extractResTable(url = urls[10], year = 2008, sex = 'male')

```
```{r}
men_2008[1:10]
men_2009[1:10]
```

```{r}
equals_idx<- grep('^===', men_2009)
equals_idx

equals_idx2<- substr(men_2009, 1,3)
which(equals_idx2 == '===')

spacerRow<- men_2009[equals_idx]
headerRow<- men_2009[equals_idx -1]
body<- men_2009[-(1:equals_idx)] # working with 2009 body
```
```{r}
head(body)
```

```{r}
headerRow<- tolower(headerRow)
headerRow
```
```{r}
# looks for first match of given sequence
ageStart<- regexec('ag', headerRow, fixed = TRUE)
ageStart
```
 "        1         1/1420             1 Ridouane Harroufi           27 Morocco                               45:56     45:56#   4:36 " 
 
 "        27 " "           " "           " "       26 M" "        26 " "     23 Ken"
```{r}
age<- substr(body, start = 49, stop = 50)
head(age)
```
```{r}
summary(as.numeric(age))
```

```{r}
#gregexpr looks for all matches of a given sequence
blankLocs<- gregexpr(' ', spacerRow)
blankLocs
```
```{r}
searchLocs<- c(0,blankLocs[[1]])
searchLocs
```

```{r}
values<- mapply(substr, list(body), start = searchLocs[-length(searchLocs)] +1, stop = searchLocs[-1] -1)
length(values)
head(values)
```
```{r}
findColLocs<- function(spacerRow){
  spaceLocs<- gregexpr(' ', spacerRow)[[1]]
  rowLength<- nchar(spacerRow)
  
  if (substring(spacerRow, rowLength, rowLength) != ' ')
    return( c(0, spaceLocs, rowLength +1))
  else return(c(0,spaceLocs))
}

locs_2012<- findColLocs(spacerRow)
length(locs_2012)
locs_2012
```
```{r}
selectCols = 
function(colNames, headerRow, searchLocs) 
{
  sapply(colNames, 
         function(name, headerRow, searchLocs)
         {
           startPos = regexpr(name, headerRow)[[1]]
           if (startPos == -1) 
             return( c(NA, NA) )
    
           index = sum(startPos >= searchLocs)
           c(searchLocs[index] + 1, searchLocs[index + 1] - 1)
         },
         headerRow = headerRow, searchLocs = searchLocs )
}
```
```{r}
searchLocs = findColLocs(spacerRow)
ageLoc = selectCols("ag", headerRow, searchLocs) 
ages = mapply(substr, list(body), 
              start = ageLoc[1,], stop = ageLoc[2, ])
summary(as.numeric(ages))
```
```{r}
shortColNames = c("name", "home", "ag", "gun", "net", "time")
locCols = selectCols(shortColNames, headerRow, searchLocs)

#mapply forms a matrix after completion
Values = mapply(substr, list(body), start = locCols[1, ], 
                stop = locCols[2, ])

class(Values)

colnames(Values) = shortColNames
head(Values)
tail(Values)[ , 1:3]
```
```{r}
extractVariables = 
  function(file, varNames =c("name", "home", "ag", "gun",
                             "net", "time"))
{
       # Find the index of the row with =s
  eqIndex = grep("^===", file)
       # Extract the two key rows and the data
  spacerRow = file[eqIndex] 
  headerRow = tolower(file[ eqIndex - 1 ])
  body = file[ -(1 : eqIndex) ]
       
       # Obtain the starting and ending positions of variables
  searchLocs = findColLocs(spacerRow)
  locCols = selectCols(varNames, headerRow, searchLocs)

  Values = mapply(substr, list(body), start = locCols[1, ], 
                  stop = locCols[2, ])
  colnames(Values) = varNames
  
  invisible(Values)
}
```
```{r}

years = 1999:2012
menTables = mapply(extractResTable, url = urls, year = years)
names(menTables) = years
```

```{r}
menResMat = lapply(menTables, extractVariables)
length(menResMat)

sapply(menResMat, nrow)
```
```{r}
sapply(menResMat, class)
```
```{r}
# how to we index this??
# a list of matrices
menResMat$`1999`[1:10,]
```
```{r}
age = as.numeric(menResMat[['2012']][ , 'ag'])

tail(age)

age = sapply(menResMat,
             function(x) as.numeric(x[ , 'ag']))

```
```{r}
boxplot(age, ylab = "Age", xlab = "Year")
```
```{r}
sapply(age,  function(x) sum(is.na(x)))
```
```{r}
# the spacing is not the same in the 2009 table
head(menTables['2001'])
```
```{r}
selectCols = function(shortColNames, headerRow, searchLocs) {
  sapply(shortColNames, function(shortName, headerRow, searchLocs){
    startPos = regexpr(shortName, headerRow)[[1]]
    if (startPos == -1) return( c(NA, NA) )
    index = sum(startPos >= searchLocs)
    c(searchLocs[index] + 1, searchLocs[index + 1])
  }, headerRow = headerRow, searchLocs = searchLocs )
}
```

```{r}
age2001 = age[["2001"]]

grep("^===", menResMat['2001'])

badAgeIndex = which(is.na(age2001)) + 5
#menTables['2001'][ badAgeIndex ]
#badAgeIndex

extractVariables = 
function(file, varNames =c("name", "home", "ag", "gun",
                           "net", "time"))
{
  
  # Find the index of the row with =s
  eqIndex = grep("^===", file)
  # Extract the two key rows and the data 
  spacerRow = file[eqIndex] 
  headerRow = tolower(file[ eqIndex - 1 ])
  body = file[ -(1 : eqIndex) ]
       # Remove footnotes and blank rows
  footnotes = grep("^[[:blank:]]*(\\*|\\#)", body)
  if ( length(footnotes) > 0 ) body = body[ -footnotes ]
  blanks = grep("^[[:blank:]]*$", body)
  if (length(blanks) > 0 ) body = body[ -blanks ]
  
  
  # Obtain the starting and ending positions of variables   
  searchLocs = findColLocs(spacerRow)
  locCols = selectCols(varNames, headerRow, searchLocs)
  
  Values = mapply(substr, list(body), start = locCols[1, ], 
                  stop = locCols[2, ])
  colnames(Values) = varNames
  
  return(Values)
}

menResMat = lapply(menTables, extractVariables)
```
```{r}
age<- sapply(menResMat, function(x) as.numeric(x[, 'ag']))
```
```{r}
sapply(age, function(x) sum(is.na(x)))
```
```{r}
boxplot(age, ylab = "Age", xlab = "Year")
```
```{r}
head(menResMat[['2001']])
```


```{r}
# length(age)
# t<- age[['2001']] < 10
# sum(t)
# young<- age[['2001']][-c(t)]
# length(young)
young<- menResMat[['2001']][,'ag'] < 10
sum(young)
menResMat[['2001']]<- menResMat[['2001']][-c(young),]
y2002<- menResMat[['2002']][,'ag'] < 10
y2003<- menResMat[['2003']][,'ag'] < 10
menResMat[['2002']]<- menResMat[['2002']][-c(y2002),]
menResMat[['2003']]<- menResMat[['2003']][-c(y2003),]
```
```{r}

y2002<- menResMat[['2002']][,'ag'] < 10
y2003<- menResMat[['2003']][,'ag'] < 10
sum(y2002)
sum(y2003)
sum(young)
```
```{r}
menResDF = lapply(menResMat, data.frame)
head(menResDF[1])

```
```{r}
col_1999 = rep(1999, nrow(menResDF$`1999`))

col_2000 = rep(2000, nrow(menResDF$`2000`))

col_2001 = rep(2001, nrow(menResDF$`2001`))

col_2002 = rep(2002, nrow(menResDF$`2002`))

col_2003 = rep(2003, nrow(menResDF$`2003`))

col_2004 = rep(2004, nrow(menResDF$`2004`))

col_2005 = rep(2005, nrow(menResDF$`2005`))

col_2006 = rep(2006, nrow(menResDF$`2006`))

col_2007 = rep(2007, nrow(menResDF$`2007`))

col_2008 = rep(2008, nrow(menResDF$`2008`))

col_2009 = rep(2009, nrow(menResDF$`2009`))

col_2010 = rep(2010, nrow(menResDF$`2010`))

col_2011 = rep(2011, nrow(menResDF$`2011`))

col_2012 = rep(2012, nrow(menResDF$`2012`))

cols = c(col_1999, col_2000, col_2001, col_2002, col_2003, col_2004, col_2005, col_2006, col_2007, col_2008, col_2009, col_2010, col_2011, col_2012)
```

```{r}
menResFinal = data.frame()
for (i in 1:length(names(menResDF))) {
  
  df<- menResDF[[i]]
  menResFinal = rbind(menResFinal, df)
}
menResFinal$Date<- cols
```

```{r}
menResFinal$ag = as.numeric(menResFinal$ag)
sum(is.na(menResFinal$ag))
```
```{r}
times = menResFinal$time
timePieces = strsplit(times, ":")

tail(timePieces)

timePieces = sapply(timePieces, as.numeric)
head(timePieces)
```
```{r}
timePieces[1:5]
class(timePieces)
timePieces[1]
```

```{r}
runTime = sapply(timePieces, 
                 function(x) {
                   if (length(x) == 2) x[1] + x[2]/60
                   else 60*x[1] + x[2] + x[3]/60
                 })

summary(runTime)
```
```{r}
convertTime = function(time) {
  timePieces = strsplit(time, ":")
  timePieces = sapply(timePieces, as.numeric)
  sapply(timePieces, function(x) {
                      if (length(x) == 2) x[1] + x[2]/60
                      else 60*x[1] + x[2] + x[3]/60
                      })
}
```
```{r}
createDF = function(Res, year, sex) 
{
  # Determine which time to use
  if ( !is.na(Res[1, 'net']) ) useTime = Res[ , 'net']
  else if ( !is.na(Res[1, 'gun']) ) useTime = Res[ , 'gun']
  else useTime = Res[ , 'time']
  
  # Remove # and * and blanks from time
  useTime = gsub("[#\\*[:blank:]]", "", useTime)
  runTime = convertTime(useTime[ useTime != "" ])
  
  # Drop rows with no time
  Res = Res[ useTime != "", ]
  
  Results = data.frame(year = rep(year, nrow(Res)),
                       sex = rep(sex, nrow(Res)),
                       name = Res[ , 'name'], home = Res[ , 'home'],
                       age = as.numeric(Res[, 'ag']), 
                       runTime = runTime,
                       stringsAsFactors = FALSE)
  invisible(Results)
}

menDF = mapply(createDF, menResMat, year = 1999:2012,
               sex = rep("M", 14), SIMPLIFY = FALSE)
```

```{r}
sapply(menDF, function(x) sum(is.na(x$runTime)))

separatorIdx = grep("^===", menTables[["2006"]])
separatorRow = menTables[['2006']][separatorIdx]
separatorRowX = paste(substring(separatorRow, 1, 63), " ", 
                      substring(separatorRow, 65, nchar(separatorRow)), 
                      sep = "")
menTables[['2006']][separatorIdx] = separatorRowX

menResMat = sapply(menTables, extractVariables)
menDF = mapply(createDF, menResMat, year = 1999:2012,
               sex = rep("M", 14), SIMPLIFY = FALSE)
```

```{r}
womenURLs = 
  c("results/1999/cb99f.html", "results/2000/Cb003f.htm", "results/2001/oof_f.html",
    "results/2002/ooff.htm", "results/2003/CB03-F.HTM",
    "results/2004/women.htm", "results/2005/CB05-F.htm", 
    "results/2006/women.htm", "results/2007/women.htm", 
    "results/2008/women.htm", "results/2009/09cucb-F.htm",
    "results/2010/2010cucb10m-F.htm", 
    "results/2011/2011cucb10m-F.htm",
    "results/2012/2012cucb10m-F.htm")

years = 1999:2012
urls = paste(ubase, womenURLs, sep = "")
urls[1:3]
womenTables = mapply(extractResTable, url = urls, year = years, sex='female')
names(womenTables) = years
sapply(womenTables, length)
```


```{r}
separatorIdx = grep("^===", womenTables[["2006"]])
separatorRow = womenTables[['2006']][separatorIdx]
separatorRowX = paste(substring(separatorRow, 1, 63), " ",
                      substring(separatorRow, 65, nchar(separatorRow)),
                      sep = "")
womenTables[['2006']][separatorIdx] = separatorRowX

womenTables[['2001']][2:3] = womenTables[['2002']][2:3]

womenResMat = sapply(womenTables, extractVariables)
womenDF = mapply(createDF, womenResMat, year = 1999:2012,
               sex = rep("W", 14), SIMPLIFY = FALSE)
```

```{r}
#head(menDF)
head(womenDF)
```
```{r}
sapply(womenDF, function(x) sum(is.na(x$age)))
```

```{r}
sapply(womenDF, function(x) sum(is.na(x$runTime)))
```
```{r}
sapply(menDF, function(x) sum(is.na(x$age)))
sapply(menDF, function(x) sum(is.na(x$runTime)))
```
```{r}
menDF_complete = na.omit(menDF)
womenDF_complete = na.omit(womenDF)
```

```{r}
cherryblossom = data.frame()
for (i in 1:14) {
  
  df<- menDF_complete[[i]]
  cherryblossom = rbind(cherryblossom, df)
}
head(cherryblossom)
```

```{r}
for (i in 1:14) {
  
  df<- womenDF_complete[[i]]
  cherryblossom = rbind(cherryblossom, df)
}
tail(cherryblossom)
```
```{r}
sum(is.na(cherryblossom))
```

```{r}
cherryblossom = na.omit(cherryblossom)
sum(is.na(cherryblossom))
```

